[package]
name = "flamebox"
version = "0.1.0"
edition = "2021"

[dependencies]
oci-spec = "0.7.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde = "1.0.216"
serde_json = "1.0.134"
